name: pub_server
version: 0.2.0
author: Dart Team <misc@dartlang.org>
description: Re-usable components for creating a custom Dart package server.
homepage: https://github.com/dart-lang/pub_server

environment:
  sdk: '>=3.0.0'

dependencies:
  http_parser: ^4.1.1
  logging: ^1.3.0
  mime: ^2.0.0
  pub_semver: ^2.1.5
  shelf: ^1.4.2
  yaml: ^3.1.2

dev_dependencies:
  archive: ^4.0.1
  args: ^2.6.0
  http: ^1.2.2
  path: ^1.5.1
  pedantic: ^1.2.0
  test: ^1.3.0
